### ISSUE TITLE
[Other]: Update issues template

### ISSUE THREAD

**Issue by Scoolnik** [Scoolnik/NR-CinematicUnityExplorer#3]
### Describe the issue

- [ ] remove required game field from bug template

**Comment by arec1b0** [comment]
I’ve addressed the request to remove the required game field. You can check the details in [Pull Request #4](https://github.com/Scoolnik/NR-CinematicUnityExplorer/pull/4). 

This should resolve the issue. Feel free to let me know if there’s anything else to improve!
